### ISSUE TITLE
Not possible to edit an existing zone in a preset

### ISSUE THREAD

**Issue by hugovangalen** [dagargo/emu3bm#4]
I have not found a way to edit an existing zone, which would be really useful. 

I had made a mistake with a note assignment and the only way to remedy this was to create an entirely new bank and redo all the work.

**Comment by dagargo** [comment]
Sorry for taking so long to answer.

emu3bm is a reverse engineering project and it was never my intention to offer a full editor but to try to discover hidden features. BTW, other than the unlimited pitch bend control I found none. However, I'm using my E-Mu again and I'm gonna try to do this.

My plan is to create a proper library inside this project to provide this kind of functionalities. The main problem is that emu3bm scans the bank files and do everything in one pass so there is no random access to a particular preset or zone or other features. So this needs a lot of rework on the structures.

First, all short options need to be long options. With this, adding new operations should be much easier, not to mention that the meaning of them will be much clearer.

**Comment by dagargo** [comment]
I've just pushed a commit that allows to delete zones in a preset.

Here is how it works.

```
$ emu3bm -e 0 --delete-zone 0 bank
```

If you're still interested in this, let me know your thoughts.

**Comment by hugovangalen** [comment]
I vaguely recollect testing this and confirming this works fine. Apparently I forgot to leave a note here.

Thanks a lot, this works very well!

**Comment by dagargo** [comment]
> Apparently I forgot to leave a note here

Nevermind, I totally forgot about this issue too.

I'm planning to add a few improvements and release version 1.0 during the summer.

If you want, star the project to keep up to date.
